### ISSUE TITLE
`data.pandora` file is not included in release builds

### ISSUE THREAD

**Issue by shomykohai** [bitbrain/pandora#184]
Godot version: 4.3 beta2

**Describe the bug**

In Godot 4.3, the `data.pandora` is not included in the exported build without explicitly declaring it in the resource tab.

**To Reproduce**
1. Make a project with pandora
2. Export the project with Godot 4.3, with and without debug build.
3. Decompile the project/print out pandora data.
4. The `data.pandora` file is not included in the final export.

Also, there are two scenarios that happens when exporting a debug build or not:
- With debug build ticked when exporting, the data.pandora file is included to the final project, but it's not guaranteed to include all entities.
- Unticking it, the data.pandora file is not included unless explicitly declared in the resource tab, and even then pandora does not print all data as it should.

**Expected behavior**
The data.pandora file should be included regardless of the export settings, and should contains all entities.

**Screenshots**

![pandora data file missing](https://github.com/bitbrain/pandora/assets/61943525/54e90004-e993-4812-80eb-f4f9fd3eeed5)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
This issue seems to be caused by some changes in Godot 4.3, which inclues a new scripts tab to the export settings that appear to break pandora based on the configuration.

**Comment by bitbrain** [comment]
This issue is caused by the fact how Pandora currently produces `data.pandora` files wrongfully:

- when Godot itself is in a `debug` build, Pandora [writes its data to a uncompressed file](https://github.com/bitbrain/pandora/blob/a4dcc34c65935f8712efd0c078dd979c0220896b/addons/pandora/storage/json/json_data_storage.gd#L28)
- when Godot itself is in a non debug build, Pandora [writes its data to a compressed file](https://github.com/bitbrain/pandora/blob/a4dcc34c65935f8712efd0c078dd979c0220896b/addons/pandora/storage/json/json_data_storage.gd#L32)

However, for exports, we do not check for the debug mode of Godot itself but [use the debug build flag for the export](https://github.com/bitbrain/pandora/blob/godot-4.x/addons/pandora/plugin.gd#L79) (debug builds can exist regardless of if Godot itself is in debug mode or not)

We need to change the behaviour as follows:

- the `data.pandora` file should ideally never be compressed inside Godot itself but only in production game exports
- when exporting a production build of your game, it should export the `data.pandora` file as compressed
- when exporting a debug build of your game, it should export the `data.pandora` file as uncompressed

This means we require a mechanism (for production builds) to convert the uncompressed pandora file into a compressed pandora file.
